const nodesPositions = [
    {
        id: 1,
        colStart: 19,
        colEnd: 20,
        rowStart: 1,
        rowEnd: 2
    },
    {
        id: 2,
        colStart: 9,
        colEnd: 10,
        rowStart: 4,
        rowEnd: 5
    },
    {
        id: 3,
        colStart: 29,
        colEnd: 30,
        rowStart: 4,
        rowEnd: 5
    },
    {
        id: 4,
        colStart: 5,
        colEnd: 6,
        rowStart: 7,
        rowEnd: 8
    },
    {
        id: 5,
        colStart: 13,
        colEnd: 14,
        rowStart: 7,
        rowEnd: 8
    },
    {
        id: 6,
        colStart: 25,
        colEnd: 26,
        rowStart: 7,
        rowEnd: 8
    },
    {
        id: 7,
        colStart: 33,
        colEnd: 34,
        rowStart: 7,
        rowEnd: 8
    },
    {
        id: 8,
        colStart: 3,
        colEnd: 4,
        rowStart: 10,
        rowEnd: 11,
    },
    {
        id: 9,
        colStart: 7,
        colEnd: 8,
        rowStart: 10,
        rowEnd: 11,
    },
    {
        id: 10,
        colStart: 11,
        colEnd: 12,
        rowStart: 10,
        rowEnd: 11,
    },
    {
        id: 11,
        colStart: 15,
        colEnd: 16,
        rowStart: 10,
        rowEnd: 11,
    },
    {
        id: 12,
        colStart: 23,
        colEnd: 24,
        rowStart: 10,
        rowEnd: 11,
    },
    {
        id: 13,
        colStart: 27,
        colEnd: 28,
        rowStart: 10,
        rowEnd: 11,
    },
    {
        id: 14,
        colStart: 31,
        colEnd: 32,
        rowStart: 10,
        rowEnd: 11,
    },
    {
        id: 15,
        colStart: 35,
        colEnd: 36,
        rowStart: 10,
        rowEnd: 11,
    },
    {
        id: 16,
        colStart: 2,
        colEnd: 3,
        rowStart: 13,
        rowEnd: 14,
    },
    {
        id: 17,
        colStart: 4,
        colEnd: 5,
        rowStart: 13,
        rowEnd: 14,
    },
    {
        id: 18,
        colStart: 6,
        colEnd: 7,
        rowStart: 13,
        rowEnd: 14,
    },
    {
        id: 19,
        colStart: 8,
        colEnd: 9,
        rowStart: 13,
        rowEnd: 14,
    },
    {
        id: 20,
        colStart: 10,
        colEnd: 11,
        rowStart: 13,
        rowEnd: 14,
    },
    {
        id: 21,
        colStart: 12,
        colEnd: 13,
        rowStart: 13,
        rowEnd: 14,
    },
    {
        id: 22,
        colStart: 14,
        colEnd: 15,
        rowStart: 13,
        rowEnd: 14,
    },
    {
        id: 23,
        colStart: 16,
        colEnd: 17,
        rowStart: 13,
        rowEnd: 14,
    },
    {
        id: 24,
        colStart: 22,
        colEnd: 23,
        rowStart: 13,
        rowEnd: 14,
    },
    {
        id: 25,
        colStart: 24,
        colEnd: 25,
        rowStart: 13,
        rowEnd: 14,
    },
    {
        id: 26,
        colStart: 26,
        colEnd: 27,
        rowStart: 13,
        rowEnd: 14,
    },
    {
        id: 27,
        colStart: 28,
        colEnd: 29,
        rowStart: 13,
        rowEnd: 14,
    },
    {
        id: 28,
        colStart: 30,
        colEnd: 31,
        rowStart: 13,
        rowEnd: 14,
    },
    {
        id: 29,
        colStart: 32,
        colEnd: 33,
        rowStart: 13,
        rowEnd: 14,
    },
    {
        id: 30,
        colStart: 34,
        colEnd: 35,
        rowStart: 13,
        rowEnd: 14,
    },
    {
        id: 31,
        colStart: 36,
        colEnd: 37,
        rowStart: 13,
        rowEnd: 14,
    },
]

export default nodesPositions;